name: multiplex-networks-diversity
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.0.7
  - cryptography=38.0.4
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.1.1
  - executing=1.2.0
  - expat=2.5.0
  - fontconfig=2.14.2
  - fonttools=4.39.4
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.2
  - glib-tools=2.76.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipykernel=6.23.1
  - ipython=8.13.2
  - jedi=0.18.2
  - jpeg=9e
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.2
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.3
  - openssl=1.1.1t
  - packaging=23.1
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - platformdirs=3.5.1
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - pytest=7.3.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.29.0
  - scipy=1.10.1
  - setuptools=67.7.2
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.42.0
  - stack_data=0.6.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - wheel=0.40.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - rustworkx==0.12.1
